views:
  - cards:
      - type: custom:fluid-level-background-card
        name: Fluid Level Background Card
        entity: input_number.battery_evel
        test_gui: true
      - type: entities
        entities:
          - input_number.battery_level
          - input_number.battery_charging
